### PR TITLE
Fix result caching on refresh and add scroll to Icon in shared links

### PR DESCRIPTION
**Pull request by ayushsatyam146**
Fixed issues mentioned in Issue #16. On refreshing the page selected Icon doesn't get lost and the selected Icon persists after Page refresh. Whenever a user opens a shared link of an icon the page auto scrolls to the shared icon and highlights the shared Icon as a selection.
I have tested all the scenarios by picking Icons from the top, middle and bottom and also from different categories.
To better illustrate the behavior a video has been attached testing all the scenarios.

https://user-images.githubusercontent.com/55888723/151445028-5563cf8b-5d01-4e14-b62d-e00cd7dde1f8.mp4

### CODE REVIEW

**Comment by vinayaksh42** [comment]
@ayushsatyam146 Great work, the scrolling to the selected icon upon sharing or re-loading the page works perfectly, but this seems to be breaking the search by tag and share by tag functionality:
https://user-images.githubusercontent.com/54861487/151486923-9fe081c9-db2f-4fdb-9348-dbe166aa184e.mp4

**Comment by ayushsatyam146** [comment]
> @ayushsatyam146 Great work, the scrolling to the selected icon upon sharing or re-loading the page works perfectly, but this seems to be breaking the search by tag and share by tag functionality (explained in video):
> 
>  De4IDSlpx4.mp4

@vinayaksh42 Thanks for mentioning the issue, added a new commit fixing this.

**Comment by vinayaksh42** [comment]
LGTM! 
@ayushsatyam146 share by tag seems to be working now

**Comment by vinayaksh42** [comment]
@ayushsatyam146 The `Test pull request` workflow keeps on failing for all the new pull requests. Would you like to have a look at it?

**Comment by vinayaksh42** [comment]
@ayushsatyam146 The scrolling feature seems not to be working in production, Kindly check with it

**Pull request merged**
