### PR TITLE
Added toast msg feature

### PR DESCRIPTION
**Pull request by StarTrooper08**
Added toast msg feature
Demo SS:

The toast msg pops up in the upper center position of the window

toastmsg2SS

### CODE REVIEW

**Comment by StarTrooper08** [comment]
Even using that I have added the feature before (now it's closed)but if I create PR again it will probably create merge conflict.
First PR I have created using toastify package but after I have gone through this https://github.com/EOS-uiux-Solutions/eos-icons-landing/pull/71 discussion and did the required changes using react-hot-toast. 
I can create PR again for the following issue using toastify package. Please share your thoughts on the following @Abhirup-99

**Comment by cyntss** [comment]
@StarTrooper08 for consistency reasons (among others discussed in #71 ) let's proceed with react-hot-toast.

**Comment by cyntss** [comment]
@Abhirup-99 can you review this PR code? I've tested the UI and everything works as expected. So final word on you!

**Comment by StarTrooper08** [comment]
Ok :+1:  @cyntss 
And PR is ready for the following issue using the `react-hot-toast` package.

**Comment by Abhirup-99** [comment]
@StarTrooper08 the code looks great, but can you move the toaster component to the top level. This would allow more reuse of the toast component.

**Comment by cyntss** [comment]
@Abhirup-99 I would like to merge this PR. Can you add an issue with your suggestions to improve the toaster?

**Pull request merged**
