### PR TITLE
Fixed link and image responsiveness issues

### LINKED ISSUE #28: Mobile Responsiveness Issues
The links, images and the table  in the mentioned screenshot are not responsive

### PR DESCRIPTION
**Pull request by AnshumanDhiman**
Fixed #28   
I have added responsiveness to the links and images which were creating the issues. in the mobile view of the eos-landing-page.
Before : - 

After :- 
ch1
ch2
ch3

### CODE REVIEW

**Comment by Abhirup-99** [comment]
@AnshumanDhiman can we have a better commit message?

**Comment by AnshumanDhiman** [comment]
I am sorry sir. Some links and images in the mobile view of the docs section of eos-landing were not responsive and were not fitting on the mobile screen and going outwards. I have fixed those issues.
Sorry for the inconvenience, I will take care next time.

**Comment by Abhirup-99** [comment]
> I am sorry sir. Some links and images in the mobile view of the docs section of eos-landing were not responsive and were not fitting on the mobile screen and going outwards. I have fixed those issues. Sorry for the inconvenience, I will take care next time.

Relax :sweat_smile:. Please update the commit message here and keep it in mind henceforth :).

**Comment by Abhirup-99** [comment]
I had asked for a change in the commit message in case you got misread.

**Comment by AnshumanDhiman** [comment]
> I had asked for a change in the commit message in case you got misread.

I have updated it sir.

**Comment by AnshumanDhiman** [comment]
Sir I have changed the commit message through git but whenever I am trying to push it to here, It is showing Permission Denied

**Comment by Abhirup-99** [comment]
You have to force push.

**Comment by AnshumanDhiman** [comment]
Is it ok now sir

**Comment by Abhirup-99** [comment]
The build seems to be failing. Can you fix it?

**Comment by AnshumanDhiman** [comment]
Sir it is showing prettier error on line 129 in Docs.js but when I am checking it, the file seems fine and in npm run test:js no error is showing. Can you help me

**Comment by Abhirup-99** [comment]
Run `npm run js:fix`

**Comment by AnshumanDhiman** [comment]
@Abhirup-99 I think its ok now sir. Thank you for helping

**Comment by Abhirup-99** [comment]
Can you merge both the commit into one?

**Comment by AnshumanDhiman** [comment]
Sir can you Squash and Merge my commit so that my both of my generated commits  can merge into one commit.

**Pull request merged**
