### PR TITLE
[Issue 10]:Search field bug in animated icons

### PR DESCRIPTION
**Pull request by capedcrusader23**
While switching to animated icons tab and selecting them, the current behaviour of code is that search field is not  populated and url also doesn't point to icon. The code fix aim to fill the input element by setting searchValue state and setting url.

### CODE REVIEW

**Comment by vinayaksh42** [comment]
@capedcrusader23 The search field as well as URL seems to be updating correctly but we also need to make the icon shareable as mentioned in https://github.com/EOS-uiux-Solutions/eos-icons-landing/issues/10.
I tested out your PR:
https://user-images.githubusercontent.com/54861487/151439533-953a1991-922e-4bd6-bfb0-624a341da80a.mp4

The URL seems to be opening the `Static Icons` tab. Instead of this it would be great if we could open the `animated Icons` tab

**Comment by vinayaksh42** [comment]
I think this will require us to add another URL parameter
for example, `type=static` or `type=animate`

**Comment by capedcrusader23** [comment]
@vinayaksh42 , i have addressed the comment please check this

**Comment by vinayaksh42** [comment]
Nice work @capedcrusader23, It seems to be working perfectly now!

**Review by vinayaksh42 — APPROVED** [review]

**Pull request merged**
