### PR TITLE
Refactored the 404 page

### LINKED ISSUE #111: 404 Error Page Re-design
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The current error page is as follows

image_2022-03-17_215628

### Expected Behavior

The text in the error page should be made more clear and re-aligned. Also a button should be added so that a user can go back to the Homepage

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### What browsers are you seeing the problem on?

_No response_

### PR DESCRIPTION
**Pull request by AnshumanDhiman**
Fixed #111 I have Refactored the 404 page and added a button to link back to the Homepage

Before

image

After

image

### CODE REVIEW

**Review by Abhirup-99 — APPROVED** [review]

**Comment by Abhirup-99** [comment]
Can you fix the build for this?

**Comment by AnshumanDhiman** [comment]
sure working on this.

**Comment by cyntss** [comment]
btw, @AnshumanDhiman I really like how well you followed the brand guidelines to create this 404 👏  👏  👏

**Comment by AnshumanDhiman** [comment]
> btw, @AnshumanDhiman I really like how well you followed the brand guidelines to create this 404 👏 👏 👏

Thank you 😇

**Comment by Abhirup-99** [comment]
@AnshumanDhiman can you close this PR? And make a new one? There are a lot of changes here.

**Comment by AnshumanDhiman** [comment]
sure

**Pull request closed without merging**
